name: KeyVault with Access Policy

on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # checkout the repo
    - uses: actions/checkout@master
    - uses: Azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS_KVSATest001 }} # Define secret variable in repository settings as per action documentation
    - uses: Azure/get-keyvault-secrets@v1
      with:
        keyvault: "KV-SATest001"
        secrets: 'mySecret1, mySecret2'
      id: myGetSecretAction
    - name: Some step to consume secrets
      run: |
          echo "${{ steps.myGetSecretAction.outputs.mySecret1 }} ${{ steps.myGetSecretAction.outputs.mySecret2 }}"
    - name: Got the secret
      run: |   
        if [ "${{ steps.myGetSecretAction.outputs.mySecret1 }}" == "mySecret2Test1" ]
        then
          echo "Got our secret"

    # - name: Create resource groups with secret values
    #   run: |
    #     az group Create --name ${{ steps.myGetSecretAction.outputs.mySecret2 }} --location uksouth
    #     # az group Create --name ${{ steps.azure-keyvault-secrets.outputs.example2 }} --location uksouth
